### ISSUE TITLE
Installation issues with pip

### ISSUE THREAD

**Issue by Wolfi-101** [SunPower/SolarUtils#9]
When trying to install solarutils on my system (Windows 10 64 bit, Miniconda with Python 3.6) I ran into several issues which I finally managed to fix for myself. Nonetheless I created this issue as a heads up.

My first attempt to use `pip install solarutils` resulted in an error telling me that I need to get the Python build tools from Microsoft Visual C++. I believe this is because there is no Python wheel for the version of Python that I am using, and `setup.py` needs a C++ compiler installed to build the required files. Enlighten me if I'm wrong here. 
Anyway, installing the build tools from the Visual Studio Community 2017 setup program got me a step further. Now after typing `pip install solarutils` the 'x64 Native Tools Command Prompt' (I read somewhere on stackoverflow that it was necessary to use this command prompt) threw a `UnicodeDecodeError`. This does not seem to be a solarutils related issue, but rather an issue with the latest version of pip since I've seen similar issues for different Python packages as well. The error message comes with another hint though: in `yourPythonPath/lib/site-packages/pip/compat/__init__.py` there is a line with `return s.decode('utf_8')`. It seems that `utf_8` is not always the right encoding. To get the correct encoding, open a new command prompt and type in the command `chcp`. It tells you the active codepage aka encoding. In my case, it told me my codepage was `850`. So in the mentioned `__init__.py` I replaced `'utf_8'` with `'cp850'`. After that solarutils installed fine.

Including all the false leads I followed until I found a solution it took me all of today to figure this out, so I though I might let you know and possibly help others save some time. I realize this is not necessarily a solarutils issue, plus I solved it for myself, so feel free to close the issue or move it somewhere else.

**Comment by mikofski** [comment]
Hi @Wolfi-101 ,

Thanks so much for your feedback! Sorry for the inconveniences you experienced installing SolarUtils. It's unfortunate that some Python packages require a C/C++ compiler, and yet this is not available by default on most systems. This is compounded by the fact that [on MS Windows each Python uses a specific version of the Visual C](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F).

I have uploaded a Python-3.6 64-bit Windows compatible Python "wheel" (see [`SolarUtils-0.2.2-cp36-cp36m-win_amd64.whl (md5)`](https://pypi.python.org/pypi/SolarUtils)) that you should be able to install just using `pip` _without needing a compiler_, and I hope this helps you and others in the future.

IMO improvements to the documentation may have helped you. Would you consider changing the issue title to something like ...

>DOC: BUG: ENH: documentation should address requirements of C compiler for each platform

... which I think would address this issue.

Then, perhaps you might [consider making this improvement yourself](http://www.thehackerwithin.org/berkeley/posts/2017-10-04-github-oss-f17.html) and submitting a [GitHub Pull Request](https://help.github.com/articles/about-pull-requests/) (_aka_ a PR)? You can actually make the changes online right in your browser by navigating to [`README.rst`](../blob/master/README.rst), and clicking the edit pencil icon
![gh_edit_pencil_icon](https://user-images.githubusercontent.com/1385621/36618116-c0ef09a0-189e-11e8-8af0-f61ff58fe502.png)
in the upper right corner of the file and creating a [web-flow edit](https://github.com/blog/1738-web-flow-editing-from-pull-requests) [quick pull request](https://github.com/blog/1945-quick-pull-requests). This will automatically fork SolarUtils to [your personal GitHub profile](../../../wolfi-101), and open a PR from your fork to the SunPower/SolarUtils master branch.

Thanks!

**Comment by mikofski** [comment]
@anomam  is this still relevant? I think as long as we push wheels for all python 3 versions, we can probably close this issue, right?

**Comment by mikofski** [comment]
@anomam, @chetan201, or @cedricleroy I think this issue can be safely closed, what do you all think?

**Comment by mikofski** [comment]
@anomam, @chetan201, or @cedricleroy I think this issue can be safely closed, what do you all think?

**Comment by anomam** [comment]
Thanks @mikofski
